//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDI_DB_FIRST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public long id { get; set; }
        public string Prénom { get; set; }
        public string Nom { get; set; }
        public int Age { get; set; }
        public int facturation { get; set; }
        public long IdClasse { get; set; }
        public string Sexe { get; set; }
    
        public virtual Classe Classe { get; set; }
    }
    public  class EtudiantView
    {
        public long id { get; set; }
        public string Prénom { get; set; }
        public string Nom { get; set; }
        public int Age { get; set; }
        public int facturation { get; set; }
        public String Classe { get; set; }
        public string Sexe { get; set; }

    
    }
}
